<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [95]:
##### Begin Working Here #####
import pandas as pd
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 100)
# df.head()

In [ ]:
!curl https://raw.githubusercontent.com/ryanleeallred/datasets/master/Ames%20Housing%20Data/train.csv

In [96]:
# df.dtypes
df['BedroomAbvGr'].head(10)

0    3
1    3
2    3
3    3
4    4
5    1
6    3
7    3
8    2
9    2
Name: BedroomAbvGr, dtype: int64

In [97]:
df['LotFrontage'].head(10)

0    65.0
1    80.0
2    68.0
3    60.0
4    84.0
5    85.0
6    75.0
7     NaN
8    51.0
9    50.0
Name: LotFrontage, dtype: float64

In [100]:
df['LotFrontage'].value_counts(dropna=False)

NaN      259
60.0     143
70.0      70
80.0      69
50.0      57
75.0      53
65.0      44
85.0      40
78.0      25
21.0      23
90.0      23
68.0      19
24.0      19
64.0      19
73.0      18
72.0      17
79.0      17
63.0      17
55.0      17
100.0     16
51.0      15
66.0      15
74.0      15
52.0      14
59.0      13
71.0      12
67.0      12
57.0      12
82.0      12
43.0      12
40.0      12
76.0      11
69.0      11
53.0      10
92.0      10
88.0      10
34.0      10
86.0      10
77.0       9
35.0       9
44.0       9
84.0       9
62.0       9
93.0       8
61.0       8
98.0       8
96.0       8
107.0      7
95.0       7
120.0      7
58.0       7
41.0       6
105.0      6
54.0       6
94.0       6
48.0       6
110.0      6
30.0       6
89.0       6
81.0       6
91.0       6
36.0       6
47.0       5
83.0       5
37.0       5
87.0       5
32.0       5
56.0       5
102.0      4
42.0       4
49.0       4
99.0       3
45.0       3
104.0      3
130.0      3
103.0      3
108.0      3
124.0      2
174.0      2
97.0       2
134.0      2
129.0      2
313.0      2
118.0      2
122.0      2
121.0      2
101.0      2
109.0      2
115.0      2
116.0      2
114.0      2
153.0      1
149.0      1
150.0      1
111.0      1
182.0      1
46.0       1
112.0      1
141.0      1
33.0       1
152.0      1
160.0      1
168.0      1
128.0      1
144.0      1
39.0       1
106.0      1
38.0       1
138.0      1
140.0      1
137.0      1
Name: LotFrontage, dtype: int64

In [ ]:
import numpy as np
# NaN is a float

# .copy() is utilized to allocate memory for a new datafram, instead of having small_df just reference sections of the previous dataframe.
small_df = df[['TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'SalePrice']].copy()

small_df.head()

In [102]:
# Create new column, easy to do since all the columns are integers
small_df['TotalSquareFootage'] = small_df['TotalBsmtSF'] + small_df['1stFlrSF'] + small_df['2ndFlrSF']
# small_df.head()

In [104]:
small_df['PricePerSqFt'] = small_df['SalePrice'] / small_df['TotalSquareFootage']
small_df['PricePerSqFt'] = small_df['PricePerSqFt'].round(2)

In [105]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-09-01 19:28:35--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 54.148.13.215, 35.161.89.82, 54.244.115.45
Connecting to resources.lendingclub.com (resources.lendingclub.com)|54.148.13.215|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.1’

LoanStats_2018Q4.cs     [               <=>  ]  22.28M  6.54MB/s    in 3.9s

2020-09-01 19:28:40 (5.72 MB/s) - ‘LoanStats_2018Q4.csv.zip.1’ saved [23360898]

In [106]:
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: LoanStats_2018Q4.csv

In [107]:
# !head LoanStats_2018Q4.csv
# !tail LoanStats_2018Q4.csv

In [119]:
dv = pd.read_csv('LoanStats_2018Q4.csv', skiprows=1)

#dv.shape
dv.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,...,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,NaN,NaN,27975.0,27975.0,27975.0,36 months,14.47%,962.52,C,C2,Conductor,10+ years,MORTGAGE,180000.0,Not Verified,Dec-2018,Fully Paid,n,NaN,NaN,credit_card,Credit card refinancing,117xx,NY,11.47,0.0,Jul-1995,0.0,39.0,NaN,10.0,0.0,29711.0,66.8%,19.0,w,0.00,0.00,31804.529849,31804.53,27975.00,3829.53,0.0,0.00,0.0000,Jan-2020,20288.02,NaN,Mar-2020,0.0,...,1.0,8.0,13.0,7.0,10.0,0.0,0.0,0.0,0.0,78.9,60.0,0.0,0.0,286525.0,45387.0,29500.0,25025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,10000.0,10000.0,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,660xx,KS,14.90,0.0,May-2007,0.0,NaN,112.0,7.0,1.0,10677.0,54.2%,12.0,w,7352.95,7352.95,4487.310000,4487.31,2647.05,1840.26,0.0,0.00,0.0000,Aug-2020,227.43,Sep-2020,Aug-2020,0.0,...,6.0,5.0,6.0,5.0,7.0,0.0,0.0,0.0,1.0,100.0,33.3,1.0,0.0,36200.0,27595.0,13000.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,28000.0,28000.0,28000.0,60 months,13.56%,645.15,C,C1,Project Manager,10+ years,MORTGAGE,128500.0,Source Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,760xx,TX,27.35,1.0,Jul-1987,0.0,24.0,NaN,16.0,0.0,55206.0,75%,31.0,w,20667.91,20667.91,12871.360000,12871.36,7332.09,5539.27,0.0,0.00,0.0000,Aug-2020,645.15,Sep-2020,Aug-2020,0.0,...,9.0,11.0,17.0,11.0,15.0,NaN,0.0,0.0,1.0,94.0,100.0,0.0,0.0,542027.0,128345.0,55000.0,60331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,16000.0,16000.0,16000.0,60 months,13.56%,368.66,C,C1,LMSW,10+ years,RENT,46000.0,Not Verified,Dec-2018,Current,n,NaN,NaN,credit_card,Credit card refinancing,787xx,TX,11.09,1.0,Oct-1997,1.0,11.0,NaN,9.0,0.0,18946.0,32.1%,21.0,w,11503.84,11503.84,7570.880000,7570.88,4496.16,3074.72,0.0,0.00,0.0000,Aug-2020,368.66,Sep-2020,Aug-2020,0.0,...,10.0,7.0,11.0,3.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,138125.0,128218.0,57600.0,79125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,7500.0,7500.0,7500.0,36 months,10.72%,244.55,B,B2,Program Manager,2 years,RENT,84000.0,Not Verified,Dec-2018,Charged Off,n,NaN,NaN,debt_consolidation,Debt consolidation,600xx,IL,3.86,0.0,May-2005,1.0,NaN,114.0,9.0,1.0,2200.0,12.6%,17.0,w,0.00,0.00,2829.930000,2829.93,1465.61,484.09,0.0,880.23,158.4414,Sep-2019,244.55,NaN,Mar-2020,0.0,...,10.0,3.0,6.0,2.0,9.0,0.0,0.0,0.0,2.0,76.5,0.0,1.0,0.0,403892.0,20833.0,17400.0,16812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN

In [120]:
dv.isnull().sum().sort_values()

inq_fi                                             2
mo_sin_old_rev_tl_op                               2
delinq_amnt                                        2
chargeoff_within_12_mths                           2
acc_open_past_24mths                               2
inq_last_12m                                       2
total_cu_tl                                        2
total_rev_hi_lim                                   2
open_rv_24m                                        2
open_rv_12m                                        2
total_bal_il                                       2
open_il_24m                                        2
open_il_12m                                        2
open_act_il                                        2
open_acc_6m                                        2
tot_cur_bal                                        2
tot_coll_amt                                       2
acc_now_delinq                                     2
application_type                                   2
policy_code                                        2
mo_sin_rcnt_rev_tl_op                              2
collections_12_mths_ex_med                         2
mo_sin_rcnt_tl                                     2
num_accts_ever_120_pd                              2
total_il_high_credit_limit                         2
total_bc_limit                                     2
total_bal_ex_mort                                  2
tot_hi_cred_lim                                    2
tax_liens                                          2
pub_rec_bankruptcies                               2
pct_tl_nvr_dlq                                     2
num_tl_op_past_12m                                 2
num_tl_90g_dpd_24m                                 2
num_tl_30dpd                                       2
num_sats                                           2
num_rev_tl_bal_gt_0                                2
num_rev_accts                                      2
num_op_rev_tl                                      2
num_il_tl                                          2
num_bc_tl                                          2
num_bc_sats                                        2
num_actv_rev_tl                                    2
num_actv_bc_tl                                     2
mort_acc                                           2
last_pymnt_amnt                                    2
max_bal_bc                                         2
collection_recovery_fee                            2
earliest_cr_line                                   2
delinq_2yrs                                        2
addr_state                                         2
zip_code                                           2
title                                              2
purpose                                            2
pymnt_plan                                         2
loan_status                                        2
issue_d                                            2
inq_last_6mths                                     2
verification_status                                2
home_ownership                                     2
sub_grade                                          2
grade                                              2
installment                                        2
int_rate                                           2
term                                               2
funded_amnt_inv                                    2
funded_amnt                                        2
loan_amnt                                          2
annual_inc                                         2
open_acc                                           2
debt_settlement_flag                               2
total_rec_int                                      2
total_rec_prncp                                    2
total_pymnt_inv                                    2
total_pymnt                                        2
pub_rec                                            2
out_prncp_inv                                      2
out_prncp                                          2
initial_list_status                                2
revol_bal                                          2
total_rec_late_fee                                 2
recoveries                                         2
total_acc                                          2
last_credit_pull_d                                 3
avg_cur_bal                                       15
all_util                                          39
revol_util                                       158
last_pymnt_d                                     161
dti                                              239
mths_since_recent_bc                            1593
bc_open_to_buy                                  1693
percent_bc_gt_75                                1694
bc_util                                         1756
num_tl_120dpd_2m                                2861
mo_sin_old_il_acct                              4480
mths_since_rcnt_il                              4480
hardship_flag                                   4788
emp_length                                     11706
mths_since_recent_inq                          16049
il_util                                        20276
emp_title                                      20949
next_pymnt_d                                   46260
mths_since_last_delinq                         72198
mths_since_recent_revol_delinq                 91632
mths_since_last_major_derog                    99234
mths_since_recent_bc_dlq                      103245
hardship_amount                               110491
hardship_payoff_balance_amount                110491
hardship_last_payment_amount                  110491
orig_projected_additional_accrued_interest    110501
annual_inc_joint                              111632
sec_app_collections_12_mths_ex_med            111632
sec_app_chargeoff_within_12_mths              111632
sec_app_num_rev_accts                         111632
sec_app_open_act_il                           111632
sec_app_open_acc                              111632
dti_joint                                     111632
sec_app_inq_last_6mths                        111632
sec_app_earliest_cr_line                      111632
revol_bal_joint                               111632
sec_app_mort_acc                              111632
sec_app_revol_util                            111890
mths_since_last_record                        112964
verification_status_joint                     113566
hardship_length                               115278
hardship_end_date                             115278
hardship_start_date                           115278
hardship_status                               115278
deferral_term                                 115278
hardship_reason                               115279
hardship_dpd                                  115279
payment_plan_start_date                       115291
hardship_type                                 115292
hardship_loan_status                          117396
sec_app_mths_since_last_major_derog           123260
debt_settlement_flag_date                     127477
settlement_status                             127477
settlement_amount                             127477
settlement_date                               127477
settlement_term                               127477
settlement_percentage                         127477
id                                            128412
desc                                          128414
url                                           128414
member_id                                     128414
dtype: int64

In [121]:
dv = dv.drop(['id', 'member_id', 'desc', 'url'], axis=1)

In [124]:
dv['int_rate']

0          14.47%
1          12.98%
2          13.56%
3          13.56%
4          10.72%
           ...
128409     13.56%
128410     11.06%
128411     16.91%
128412        NaN
128413        NaN
Name: int_rate, Length: 128414, dtype: object

In [128]:
# Function to apply on column
def int_rate_to_float(int_rate):
  if isinstance(int_rate, str):
    return float(int_rate.strip().strip('%'))
  else:
    return 'Unknown'

In [129]:
dv['int_rate'].apply(int_rate_to_float)

0           14.47
1           12.98
2           13.56
3           13.56
4           10.72
           ...
128409      13.56
128410      11.06
128411      16.91
128412    Unknown
128413    Unknown
Name: int_rate, Length: 128414, dtype: object

In [ ]:
def clean_emp_title(title):
  if isinstance(title, str):
    return title.strip().title()
  else:
    return 'Unknown'


for title in examples:
  print(clean_emp_title(title))

In [130]:
dv['emp_title_cleaned'] = dv['emp_title'].apply(clean_emp_title)
dv.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_title_cleaned
0,27975.0,27975.0,27975.0,36 months,14.47%,962.52,C,C2,Conductor,10+ years,MORTGAGE,180000.0,Not Verified,Dec-2018,Fully Paid,n,credit_card,Credit card refinancing,117xx,NY,11.47,0.0,Jul-1995,0.0,39.0,NaN,10.0,0.0,29711.0,66.8%,19.0,w,0.00,0.00,31804.529849,31804.53,27975.00,3829.53,0.0,0.00,0.0000,Jan-2020,20288.02,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,...,8.0,13.0,7.0,10.0,0.0,0.0,0.0,0.0,78.9,60.0,0.0,0.0,286525.0,45387.0,29500.0,25025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Conductor
1,10000.0,10000.0,10000.0,60 months,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0.0,May-2007,0.0,NaN,112.0,7.0,1.0,10677.0,54.2%,12.0,w,7352.95,7352.95,4487.310000,4487.31,2647.05,1840.26,0.0,0.00,0.0000,Aug-2020,227.43,Sep-2020,Aug-2020,0.0,NaN,1.0,Individual,NaN,...,5.0,6.0,5.0,7.0,0.0,0.0,0.0,1.0,100.0,33.3,1.0,0.0,36200.0,27595.0,13000.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Printer
2,28000.0,28000.0,28000.0,60 months,13.56%,645.15,C,C1,Project Manager,10+ years,MORTGAGE,128500.0,Source Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,760xx,TX,27.35,1.0,Jul-1987,0.0,24.0,NaN,16.0,0.0,55206.0,75%,31.0,w,20667.91,20667.91,12871.360000,12871.36,7332.09,5539.27,0.0,0.00,0.0000,Aug-2020,645.15,Sep-2020,Aug-2020,0.0,71.0,1.0,Individual,NaN,...,11.0,17.0,11.0,15.0,NaN,0.0,0.0,1.0,94.0,100.0,0.0,0.0,542027.0,128345.0,55000.0,60331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Project Manager
3,16000.0,16000.0,16000.0,60 months,13.56%,368.66,C,C1,LMSW,10+ years,RENT,46000.0,Not Verified,Dec-2018,Current,n,credit_card,Credit card refinancing,787xx,TX,11.09,1.0,Oct-1997,1.0,11.0,NaN,9.0,0.0,18946.0,32.1%,21.0,w,11503.84,11503.84,7570.880000,7570.88,4496.16,3074.72,0.0,0.00,0.0000,Aug-2020,368.66,Sep-2020,Aug-2020,0.0,NaN,1.0,Individual,NaN,...,7.0,11.0,3.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,138125.0,128218.0,57600.0,79125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Lmsw
4,7500.0,7500.0,7500.0,36 months,10.72%,244.55,B,B2,Program Manager,2 years,RENT,84000.0,Not Verified,Dec-2018,Charged Off,n,debt_consolidation,Debt consolidation,600xx,IL,3.86,0.0,May-2005,1.0,NaN,114.0,9.0,1.0,2200.0,12.6%,17.0,w,0.00,0.00,2829.930000,2829.93,1465.61,484.09,0.0,880.23,158.4414,Sep-2019,244.55,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,...,3.0,6.0,2.0,9.0,0.0,0.0,0.0,2.0,76.5,0.0,1.0,0.0,403892.0,20833.0,17400.0,16812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Program Manager

In [ ]:
# dv['issue_d']

In [133]:
dv['issue_d'] =  pd.to_datetime(dv['issue_d'], infer_datetime_format=True)
# dv['issue_d'].head()

In [134]:
dv['issue_d'][0]

Timestamp('2018-12-01 00:00:00')

In [136]:
dv['issue_d'].dt.month

0         12.0
1         12.0
2         12.0
3         12.0
4         12.0
          ...
128409    10.0
128410    10.0
128411    10.0
128412     NaN
128413     NaN
Name: issue_d, Length: 128414, dtype: float64

In [137]:
dv['term'].head()

0     36 months
1     60 months
2     60 months
3     60 months
4     36 months
Name: term, dtype: object

In [139]:
def term_to_flt(term):
  if isinstance(term, str):
    return float(term.strip("months"))
  else:
    return 'Unknown'

In [140]:
dv['term'] = dv['term'].apply(term_to_flt)

In [141]:
# dv.head()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,...,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,emp_title_cleaned
0,27975.0,27975.0,27975.0,36,14.47%,962.52,C,C2,Conductor,10+ years,MORTGAGE,180000.0,Not Verified,2018-12-01,Fully Paid,n,credit_card,Credit card refinancing,117xx,NY,11.47,0.0,Jul-1995,0.0,39.0,NaN,10.0,0.0,29711.0,66.8%,19.0,w,0.00,0.00,31804.529849,31804.53,27975.00,3829.53,0.0,0.00,0.0000,Jan-2020,20288.02,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,...,8.0,13.0,7.0,10.0,0.0,0.0,0.0,0.0,78.9,60.0,0.0,0.0,286525.0,45387.0,29500.0,25025.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Conductor
1,10000.0,10000.0,10000.0,60,12.98%,227.43,B,B5,Printer,9 years,RENT,60000.0,Not Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,660xx,KS,14.90,0.0,May-2007,0.0,NaN,112.0,7.0,1.0,10677.0,54.2%,12.0,w,7352.95,7352.95,4487.310000,4487.31,2647.05,1840.26,0.0,0.00,0.0000,Aug-2020,227.43,Sep-2020,Aug-2020,0.0,NaN,1.0,Individual,NaN,...,5.0,6.0,5.0,7.0,0.0,0.0,0.0,1.0,100.0,33.3,1.0,0.0,36200.0,27595.0,13000.0,16500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Printer
2,28000.0,28000.0,28000.0,60,13.56%,645.15,C,C1,Project Manager,10+ years,MORTGAGE,128500.0,Source Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,760xx,TX,27.35,1.0,Jul-1987,0.0,24.0,NaN,16.0,0.0,55206.0,75%,31.0,w,20667.91,20667.91,12871.360000,12871.36,7332.09,5539.27,0.0,0.00,0.0000,Aug-2020,645.15,Sep-2020,Aug-2020,0.0,71.0,1.0,Individual,NaN,...,11.0,17.0,11.0,15.0,NaN,0.0,0.0,1.0,94.0,100.0,0.0,0.0,542027.0,128345.0,55000.0,60331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Project Manager
3,16000.0,16000.0,16000.0,60,13.56%,368.66,C,C1,LMSW,10+ years,RENT,46000.0,Not Verified,2018-12-01,Current,n,credit_card,Credit card refinancing,787xx,TX,11.09,1.0,Oct-1997,1.0,11.0,NaN,9.0,0.0,18946.0,32.1%,21.0,w,11503.84,11503.84,7570.880000,7570.88,4496.16,3074.72,0.0,0.00,0.0000,Aug-2020,368.66,Sep-2020,Aug-2020,0.0,NaN,1.0,Individual,NaN,...,7.0,11.0,3.0,9.0,0.0,0.0,0.0,1.0,94.7,20.0,0.0,0.0,138125.0,128218.0,57600.0,79125.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Lmsw
4,7500.0,7500.0,7500.0,36,10.72%,244.55,B,B2,Program Manager,2 years,RENT,84000.0,Not Verified,2018-12-01,Charged Off,n,debt_consolidation,Debt consolidation,600xx,IL,3.86,0.0,May-2005,1.0,NaN,114.0,9.0,1.0,2200.0,12.6%,17.0,w,0.00,0.00,2829.930000,2829.93,1465.61,484.09,0.0,880.23,158.4414,Sep-2019,244.55,NaN,Mar-2020,0.0,NaN,1.0,Individual,NaN,...,3.0,6.0,2.0,9.0,0.0,0.0,0.0,2.0,76.5,0.0,1.0,0.0,403892.0,20833.0,17400.0,16812.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,Program Manager

In [142]:
dv['loan_status']

0          Fully Paid
1             Current
2             Current
3             Current
4         Charged Off
             ...
128409        Current
128410        Current
128411        Current
128412            NaN
128413            NaN
Name: loan_status, Length: 128414, dtype: object

In [143]:
def loan_is_great(loan):
  if loan == "Current" or loan == "Fully Paid":
    return 1
  else:
    return 0

In [145]:
dv['loan_status_is_great'] = dv['loan_status'].apply(loan_is_great)

In [146]:
# dv['loan_status_is_great'].head(10)

0    1
1    1
2    1
3    1
4    0
5    1
6    1
7    1
8    1
9    1
Name: loan_status_is_great, dtype: int64

In [148]:
dv['last_pymnt_d'].head()

0    Jan-2020
1    Aug-2020
2    Aug-2020
3    Aug-2020
4    Sep-2019
Name: last_pymnt_d, dtype: object

In [153]:
dv['last_pymnt_d'] = pd.to_datetime(dv['last_pymnt_d'], infer_datetime_format=True)

In [154]:
dv['last_pymnt_d_month'] = dv['last_pymnt_d'].dt.month
dv['last_pymnt_d_year'] = dv['last_pymnt_d'].dt.year

In [157]:
# dv['last_pymnt_d_month'].head()
# dv['last_pymnt_d_year'].head()

0    1.0
1    8.0
2    8.0
3    8.0
4    9.0
Name: last_pymnt_d_month, dtype: float64

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [ ]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [ ]:
# %cd instacart_2017_05_01